version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      front_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_vers}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
#      - 9292:9292/tcp  
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_vers}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_vers}
    networks:
      - front_net
      - back_net
volumes:
  post_db:

networks:
  back_net:
  front_net:
