global:
  slack_api_url: "https://hooks.slack.com/services/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"

route:
  receiver: 'slack-notifications'

receivers:
- name: "slack-notifications"
  slack_configs:
  - channel: "#devops"
    
#email_configs:
#  - to: divakovn@gmail.com
#    from: avtoamato@gmail.com
#    smarthost: smtp.gmail.com:587
#    auth_username: "avtoamato@gmail.com"
#    auth_identity: "avtoamato@gmail.com"
#    auth_password: "Amato_key_888"
