{
 "title": "UI_SERVICE_MONITORING Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Histogramm",
   "type": "graph",
   "description": "Procent historgamm 95",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_latency_seconds_bucket[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "HTTP Requests error",
   "type": "graph",
   "description": "All error for service ui",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[5m])"
    }
   ]
  },
  {
   "title": "UI HTTP  Requests",
   "type": "graph",
   "description": "All HTTP Requests  that UI service receives",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ui_request_count" }
   ]
  }
 ]
}